services:
  jekyll:
    image: jekyll/jekyll:latest
    command: sh -c "bundle install && bundle exec jekyll serve --host 0.0.0.0 --livereload"
    ports:
      - '4000:4000'
      - '35729:35729'
    volumes:
      - .:/srv/jekyll
    environment:
      - TZ=Pacific/Auckland
